### ISSUE TITLE
Dark Mode / Light Mode toggle

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#54]
The codebase needs a convention for color variables that allows us to easily switch dark & light mode.

Currently I use css variables for all colors, so this shouldn't be too difficult to enhance.
I think we only need to use js to toggle a css class somewhere.

We don't have completed light theme designs yet, but we can improvise until then. We can comment out a UI switch until it's ready.

```css
:root.theme-default {
 --surface: #121212;
 --surface-01: #1e1e1e;
 --primary: #33972d;
 --primary-variant: #33732f;
 --secondary: #14c3b9;
 --secondary-variant: #1ea39b;
}
:root.theme-light {
 --surface: #??????;
 --surface-01: #??????;
 --primary: #??????;
 --primary-variant: #??????;
 --secondary: #??????;
 --secondary-variant: #??????;
}
```

Hopefully don't need to mess with existing CSS too much, but there could be some missing color pairs.

A stretch-goal might be to extract this to a drop-in component, and export it from `lib/components` so it can be used in both `app` and `site`.

```tsx
// app/pages/_app.tsx
<InjectThemeVariables />
```

Toggle button can probably be pretty simple?

```
const ColorModeSwitch = () => {
  const handleClick = () => {
    // set className on root
  }

  return <button onClick={handleClick} className={styles.colorModeSwitch} />
}

```
